theme = "catppuccin_mocha"

[editor]
line-number = "relative"
middle-click-paste = false
color-modes = true

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = false

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "spinner"]
center = []
right = ["diagnostics"]
mode.normal = "[NORMAL]"
mode.insert = "[INSERT]"
mode.select = "[SELECT]"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 1000

[editor.inline-diagnostics]
cursor-line = "disable"
other-lines = "disable"

[keys.normal]
L = ["collapse_selection", "extend_to_line_end"]
H = ["collapse_selection","extend_to_line_start"]
J = "goto_last_line"
K = "goto_file_start"

p = "paste_after"
P = "paste_after"
x = "extend_to_line_bounds"

e = "select_regex"

ret = "add_newline_below"
S-ret = "add_newline_above"
"}" = "goto_next_function"
"{" = "goto_prev_function"

esc = "collapse_selection"
tab = "rotate_view"

"~" = ["ensure_selections_forward", "flip_selections", "collapse_selection", "switch_case"]

[keys.select]
L = ["collapse_selection", "extend_to_line_end"]
H = ["collapse_selection","extend_to_line_start"]
J = "goto_last_line"
K = "goto_file_start"

p = "paste_after"
P = "paste_after"
x = "extend_to_line_bounds"

ret = "add_newline_below"
S-ret = "add_newline_above"
"}" = "goto_next_function"
"{" = "goto_prev_function"

tab = "rotate_view"

[keys.normal.space]
n = ["vsplit_new", "file_picker"]
x = ":wqa!"
q = ":wq"

e = "hover"
s = ":format"
m = "goto_implementation"

p = ["open_below", "paste_clipboard_after"]
